version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - db_data:/var/lib/mssql
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 'PassW@rd'
    ports:
      - "1433:1433"

  phpmyadmin:
    depends_on:
      - mssql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mssql
    restart: always
    ports:
      - "8080:80"
        
  php-apache:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mssql

volumes:
  db_data: {}
